"""empty message

Revision ID: 239713ea76bf
Revises: 
Create Date: 2024-07-06 16:42:52.729014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239713ea76bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrations',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=False),
    sa.Column('admin_pwd', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=70), nullable=False),
    sa.Column('admin_signupdate', sa.DateTime(), nullable=True),
    sa.Column('admin_lastlogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('clothingtypes',
    sa.Column('clothingtype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clothingtype_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('clothingtype_id')
    )
    op.create_table('localgovernments',
    sa.Column('lg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lg_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('lg_id')
    )
    op.create_table('requestdetails',
    sa.Column('rqstdetail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rqstdetail_qty_of_serv', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('rqstdetail_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('services',
    sa.Column('serv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serv_name', sa.String(length=200), nullable=False),
    sa.Column('serv_image', sa.String(length=255), nullable=False),
    sa.Column('serv_description', sa.String(length=255), nullable=False),
    sa.Column('serv_price', sa.Float(), nullable=False),
    sa.Column('serv_status', sa.Enum('1', '0'), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('serv_id')
    )
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('dispatchers',
    sa.Column('dispatcher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatcher_email', sa.String(length=100), nullable=False),
    sa.Column('dispatcher_username', sa.String(length=40), nullable=False),
    sa.Column('dispatcher_password', sa.String(length=255), nullable=False),
    sa.Column('dispatcher_businessname', sa.String(length=80), nullable=False),
    sa.Column('dispatcher_officeaddress', sa.String(length=200), nullable=False),
    sa.Column('dispatcher_businessregdate', sa.Date(), nullable=True),
    sa.Column('dispatcher_certofreg', sa.String(length=100), nullable=True),
    sa.Column('dispatcher_idcard', sa.Integer(), nullable=True),
    sa.Column('dispatcher_bankname', sa.String(length=100), nullable=True),
    sa.Column('dispatcher_accountno', sa.String(length=100), nullable=True),
    sa.Column('dispatcher_price', sa.String(length=80), nullable=True),
    sa.Column('dispatcher_status', sa.Enum('pending', 'success', 'failed'), nullable=False),
    sa.Column('dispatcher_platenumber', sa.String(length=15), nullable=True),
    sa.Column('dispatcher_lg', sa.Integer(), nullable=True),
    sa.Column('dispatcher_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_lg'], ['localgovernments.lg_id'], ),
    sa.ForeignKeyConstraint(['dispatcher_state'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('dispatcher_id'),
    sa.UniqueConstraint('dispatcher_email')
    )
    op.create_table('drycleaners',
    sa.Column('drycleaner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drycleaner_email', sa.String(length=100), nullable=False),
    sa.Column('drycleaner_username', sa.String(length=40), nullable=False),
    sa.Column('drycleaner_password', sa.String(length=255), nullable=False),
    sa.Column('drycleaner_businessname', sa.String(length=80), nullable=False),
    sa.Column('drycleaner_officeaddress', sa.String(length=200), nullable=False),
    sa.Column('drycleaner_businessregdate', sa.Date(), nullable=True),
    sa.Column('drycleaner_certofreg', sa.Integer(), nullable=True),
    sa.Column('drycleaner_bankname', sa.String(length=100), nullable=True),
    sa.Column('drycleaner_accountno', sa.String(length=100), nullable=True),
    sa.Column('dispatcher_price', sa.String(length=80), nullable=True),
    sa.Column('drycleaner_status', sa.Enum('pending', 'sucecess', 'failed'), nullable=False),
    sa.Column('drycleaner_lg', sa.Integer(), nullable=True),
    sa.Column('drycleaner_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drycleaner_lg'], ['localgovernments.lg_id'], ),
    sa.ForeignKeyConstraint(['drycleaner_state'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('drycleaner_id'),
    sa.UniqueConstraint('drycleaner_email')
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_image', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_status', sa.Enum('1', '0'), server_default='0', nullable=True),
    sa.Column('item_clothingtype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_clothingtype'], ['clothingtypes.clothingtype_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=100), nullable=False),
    sa.Column('user_lname', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_username', sa.String(length=40), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_dob', sa.DateTime(), nullable=True),
    sa.Column('user_phone', sa.String(length=15), nullable=False),
    sa.Column('user_address', sa.String(length=100), nullable=True),
    sa.Column('user_pix', sa.String(length=120), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('user_regdate', sa.DateTime(), nullable=True),
    sa.Column('user_lg', sa.Integer(), nullable=True),
    sa.Column('user_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_lg'], ['localgovernments.lg_id'], ),
    sa.ForeignKeyConstraint(['user_state'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_userid', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed'), nullable=False),
    sa.Column('payment_payer', sa.String(length=200), nullable=True),
    sa.Column('payment_email', sa.String(length=120), nullable=True),
    sa.Column('payment_ref', sa.String(length=200), nullable=True),
    sa.Column('payment_paygate', sa.String(length=200), nullable=True),
    sa.Column('payment_dateupdated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_userid'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_createddate', sa.DateTime(), nullable=False),
    sa.Column('request_processeddate', sa.DateTime(), nullable=True),
    sa.Column('pickedup_status', sa.Enum('pending', 'accepted', 'pickedup', 'delivered'), nullable=True),
    sa.Column('delivered_status', sa.Enum('pending', 'pickedup', 'delivered'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('dispatcher_id', sa.Integer(), nullable=True),
    sa.Column('drycleaner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatchers.dispatcher_id'], ),
    sa.ForeignKeyConstraint(['drycleaner_id'], ['drycleaners.drycleaner_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('wainitems',
    sa.Column('wainitem_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wainitem_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wainitems')
    op.drop_table('requests')
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('drycleaners')
    op.drop_table('dispatchers')
    op.drop_table('states')
    op.drop_table('services')
    op.drop_table('roles')
    op.drop_table('requestdetails')
    op.drop_table('localgovernments')
    op.drop_table('clothingtypes')
    op.drop_table('administrations')
    # ### end Alembic commands ###
