"""empty message

Revision ID: 27df711a3390
Revises: f09bfbc032bf
Create Date: 2024-07-06 19:16:41.857248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27df711a3390'
down_revision = 'f09bfbc032bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatcher_pix', sa.String(length=120), nullable=True))

    with op.batch_alter_table('drycleaners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drycleaner_pix', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('drycleaner_phone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drycleaners', schema=None) as batch_op:
        batch_op.drop_column('drycleaner_phone')
        batch_op.drop_column('drycleaner_pix')

    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.drop_column('dispatcher_pix')

    # ### end Alembic commands ###
