"""empty message

Revision ID: f09bfbc032bf
Revises: 239713ea76bf
Create Date: 2024-07-06 17:41:08.530621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09bfbc032bf'
down_revision = '239713ea76bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatcher_phone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatchers', schema=None) as batch_op:
        batch_op.drop_column('dispatcher_phone')

    # ### end Alembic commands ###
